# Blocks edits whose target is hosts/nixos/hardware-configuration.nix.
# Only a string that is itself such a path, or a Codex apply_patch file
# header, counts, so content that merely mentions the file passes.
target='hosts/nixos/hardware-configuration\.nix'
if jq -e --arg t "$target" 'any(.. | strings; test("(^|/)" + $t + "$") or test("\\*\\*\\* (Update|Add|Delete) File: [^\\n]*" + $t))' >/dev/null; then
  echo "Blocked: hosts/nixos/hardware-configuration.nix is generated by nixos-generate-config. Put overrides in hosts/nixos/configuration.nix instead." >&2
  exit 2
fi
